### ISSUE TITLE
Installation max key length error

### ISSUE THREAD

**Issue by newbie2005** [LaravelDaily/quickadmin#101]
I use Mysql, it shown error in installation
 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
   (SQL: alter table `users` add unique `users_email_unique`(`email`))

**Comment by PovilasKorop** [comment]
@newbie2005 this is error related to MySQL, not to QuickAdmin.

Quote from the official docs:
"Prefix support and lengths of prefixes (where supported) are storage engine dependent. For example, a prefix can be up to 767 bytes long for InnoDB tables or 3072 bytes if the innodb_large_prefix option is enabled. For MyISAM tables, the prefix limit is 1000 bytes. "

Please read here [https://dev.mysql.com/doc/refman/5.7/en/create-index.html](url) or google for "Specified key was too long; max key length is 767 bytes" - there are a lot of forum topics.
