### ISSUE TITLE
how can edit fields

### ISSUE THREAD

**Issue by sehsah** [LaravelDaily/quickadmin#102]
hi,
can u help me to edite fields when i edite menu
i cant Title , Roles, Icon 

but fields not found !

**Comment by PovilasKorop** [comment]
@sehsah we don't allow to edit fields in our package.

**Comment by sehsah** [comment]
okey thanks :) 
i developed package and add more option to make it easy

**Comment by PovilasKorop** [comment]
@sehsah great :) we went another way and field editing (and a lot more) made into our online generator version [QuickAdminPanel.com](https://quickadminpanel.com)

**Comment by tpharaoh** [comment]
Allow me a marketing plug for you povilas

I love your package but I prefer your online version. I like the idea that
what I get is a clean laravel no package, no learning curve, just step one
of code.

I use both. But now almost exclusively your online. And I always recommend
it. The annual license is more than reasonable and if for any reason (i.e.
No credit card) someone can't pay the license the generated code is visible
for free just not downloadable as installation package.

Almost seems your are doing a public service with it :)

**Comment by PovilasKorop** [comment]
Thanks for the "natural" marketing, that's the best way - to ask customer's opinion :)

To be honest, you've described it really well - in short, this Github is a *package*, and online version is a *service* (including live-chat support, consultations, updates, bugfixes etc.)
