### ISSUE TITLE
 There are no commands defined in the "quickadmin" namespace.

### ISSUE THREAD

**Issue by cikaRadule** [LaravelDaily/quickadmin#104]
Hi everyone,

I've completed the steps from the instructions but for some reason, I'm not able to invoke 'php artisan quickadmin:install'. Artisan states that " There are no commands defined in the "quickadmin" namespace."

I've tried to google it out, but failed to find any similar issues reported until now...
Do you have any suggestion what might have gone wrong? I've used it on clean Laravel install.
PHP is at version 5.6.25
Laravel is 5.4.15

**Comment by ModestasV** [comment]
Hello,

Have you added `Laraveldaily\Quickadmin\QuickadminServiceProvider::class,` to your `\config\app.php`?

**Comment by cikaRadule** [comment]
Hi,

As it was mentioned in the steps, I've added that line just below RouteServiceProvider::class.
But, just noticed that I've got too familiar with stupid AndroidStudio and his auto-save feature that I forgot to save the change :)

Now I've got the following issue:
"SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes (SQL: alter table `users` add unique
  `users_email_unique`(`email`))"

I've found that the problem is, as stated, too long key. But, as it's also mentioned, if one is using MySQL version at least 5.7 (as I'm using 5.7.14) it should not be a problem.
Trying to set "set global innodb_large_prefix=on; set global innodb_file_format=Barracuda;" also did not help my case... Do you maybe have any suggestion for that issue?

Db collation is utf8_unicode_ci

**Comment by ModestasV** [comment]
Interesting as you should not have such issues. 

Anyways, you can always reffer to this tutorial and fix database related issues: https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by cikaRadule** [comment]
Thanks so much for the help :)
