### ISSUE TITLE
How to restrict admin for non admin user

### ISSUE THREAD

**Issue by Monilal** [LaravelDaily/quickadmin#105]
Hi, 

I'm trying to to restrict non Administrator user but not working, 

`    public function handle($request, Closure $next, $guard = null)
    {
        if(Auth::check()){
            if (Auth::user()->isAdmin()){
                return redirect('/admin');
            }
        }

        return $next($request);
    }
}`

**Comment by PovilasKorop** [comment]
@Monilal what do you mean non-administrator user, it is restricted in our package - you're probably doing something outside of our package logic.

**Comment by Monilal** [comment]
Like I have 3 user roles Administrator, User, Operator. if user role is Administrator than its can redirect to locathost:8080/admin otherwise its redirect to locathost:8080/home page, actually I'm trying to do only  Administrator can access /admin URL. How can I do it.

**Comment by PovilasKorop** [comment]
This question is outside of our package functionality, it's in Laravel code, we don't provide such support.

**Comment by Monilal** [comment]
thank you
