### ISSUE TITLE
Where I can reach the created controller 's routes?

### ISSUE THREAD

**Issue by qeifar** [LaravelDaily/quickadmin#107]
I crete new crud menu, then it produce Model, Controller and views.. but theres no route how to adjust the route?

**Comment by PovilasKorop** [comment]
@qeifar Routes are being built dynamically by menu items, inside the package, see here: https://github.com/LaravelDaily/quickadmin/blob/master/src/routes.php  

You can add your own routes "on top" in your routes file.

**Comment by qeifar** [comment]
Hmm.. I am a lil blurred.. may u provide some picture to describe it.? And, dynamic did u meant the generator didnt generate route? Sorry. Thank You very much

**Comment by ModestasV** [comment]
@qeifar Yes, there is no visible routes for you to see on our package as they are generated deep in the code.

To simply adjust it - you can rewrite the needed routes in your route file and everything will work as you need it to work
