### ISSUE TITLE
change text to select

### ISSUE THREAD

**Issue by qeifar** [LaravelDaily/quickadmin#108]
Hi +PovilasKorop,
May i know how to put select as one of the datatype rather than datepicker, text area and else?

**Comment by PovilasKorop** [comment]
@qeifar we have field types 'relationship' and 'enum' for this. See here: https://github.com/LaravelDaily/quickadmin/blob/master/src/Fields/FieldsDescriber.php

**Comment by qeifar** [comment]
Thank You for you reply :D. But, if I want to make a select, which was the best one to choose?

![a](https://cloud.githubusercontent.com/assets/13729734/25422425/71af928c-2a93-11e7-96c7-78481546a2f5.PNG)

**Comment by PovilasKorop** [comment]
enum probably
