### ISSUE TITLE
Error after a install

### ISSUE THREAD

**Issue by ignasbernotas** [LaravelDaily/quickadmin#11]
Everything installed just fine, but after logging in and visiting either crud or users I get the following error. Installed this on Laravel 5.1.x-dev 425fe00. Any ideas? :)

BadMethodCallException in Builder.php line 2073:
Call to undefined method Illuminate\Database\Query\Builder::permissionCan()

**Comment by dedurus** [comment]
Same here, but different error: 
    `ReflectionException in Container.php line 737: Class role does not exist`

**Comment by PovilasKorop** [comment]
Hi @ignasbernotas - I've just tested it all again, it all works well for me. I think that Laravel version that you're using is a little older - Authorization features with permissions were added in 5.1.11:
http://laravel.com/docs/5.1/authorization
"Note: Authorization was added in Laravel 5.1.11, please refer to the upgrade guide before integrating these features into your application."

I guess we should add this requirement to our documentation.

**Comment by Jeroen-G** [comment]
As far as I see the error has to do with the function defined in `src/Traits/AdminPermissionsTrait.php` and not with a Laravel authorization function (which is `can()`, not `permissionCan()`).
It seems the function/trait is not present on the model [according to the error](http://php.net/manual/en/class.badmethodcallexception.php).

**Comment by ModestasV** [comment]
I've located this bug. This is due that our middleware tries to check user data while user is not logged in. I have this bug fixed but there will be a short time till it is released (we are working on a bigger update now).

Thank you for this report and have a nice day!

**Comment by ignasbernotas** [comment]
One suggestion. This package shouldn't be so intrusive. By that I mean, it shouldn't overwrite the models, but rather have instructions on what traits, keys or relationships should be added to the model, or even better, there should be separate models extending the existing ones.

Thoughts? :)

**Comment by PovilasKorop** [comment]
Thanks for suggestion @ignasbernotas - it makes sense in general, but that's not what we're trying to build here. QuickAdmin is a GENERATOR package which people should use after fresh Laravel install. And then you can build on top of that - if you need more logic or something to be different - your models etc. 
The goal here is that final result would be pure Laravel MVC code, not Quickadmin code - therefore people don't need to learn our structure or read our documentation, they generate what they need and then move on with their logic.
