### ISSUE TITLE
How do I remove the created crud?

### ISSUE THREAD

**Issue by ztvMark** [LaravelDaily/quickadmin#110]
How do I remove the created crud? I do not get that option

I accidentally add one which files should I delete?

**Comment by PovilasKorop** [comment]
@ztvMark you're right, we don't have that function visually, you need to delete all related MVC files and database entry in cruds table.

**Comment by PovilasKorop** [comment]
@ztvMark that's actually the reason why we've built an online version where you can edit/delete CRUDs [quickadminpanel.com](https://quickadminpanel.com)
