### ISSUE TITLE
Laravel Migration Error: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by moon759** [LaravelDaily/quickadmin#112]
Using Laravel 5.4 i have face this issue , and  this cmd :  php artisan quickadmin:install  gives the above error 
now i have changed the  /app/database.php file under mysql section 
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
//'charset' => 'utf8mb4',
 // 'collation' => 'utf8mb4_unicode_ci',

now cmd is working

**Comment by PovilasKorop** [comment]
@moon759 Laravel News wrote about it in Laravel 5.4: https://laravel-news.com/laravel-5-4-key-too-long-error
