### ISSUE TITLE
I have the table user already created

### ISSUE THREAD

**Issue by jiac0911** [LaravelDaily/quickadmin#113]
I want to implement the admin panel but I already have an users table this table doesn't have the remember toke, and instead of rol_id y have a column called tipo_usuario_id (it has the same goal but this database is in spanish) so I instead of roles table i have tipo_usuarios table, and I have a lot of different problems like that, so can I adapt it or it is just imposible?

**Comment by PovilasKorop** [comment]
@jiac0911 one sentence from Readme file: "Please note: QuickAdmin requires fresh Laravel installation and is not suitable for use on already existing project."
