### ISSUE TITLE
menus.menu_type

### ISSUE THREAD

**Issue by unstoppablecarl** [LaravelDaily/quickadmin#116]
It does not appear to be documented anywhere (including in code) what this column does. I see that it is checked in many places to be 0-3 but cannot easily understand what each value represents.

**Comment by PovilasKorop** [comment]
@unstoppablecarl in theory, you shouldn't be working with those numbers directly, visual CRUD generator should be enough. 

1 - Typical CRUD
2 - Parent menu
3 - Custom menu
0 - Any other menu (hidden or something)

**Comment by unstoppablecarl** [comment]
I was just looking at the source and trying to follow how it worked.
