### ISSUE TITLE
 "Class 'Yajra\Datatables\Datatables' not found" after upgrade from laravel 5.4 to 5.5

### ISSUE THREAD

**Issue by lgt** [LaravelDaily/quickadmin#118]
After upgrading to laravel 5.4 and requesting datatables 8 I get this error message in console

**Comment by PovilasKorop** [comment]
@lgt we currently don't support other Datatables version than 6
We're going to upgrade package to 5.5 probably next week.

**Comment by lgt** [comment]
Thank you for feedback!
