### ISSUE TITLE
laravel 5.4 admin/menu/crud Undefined property: stdClass::$column_name

### ISSUE THREAD

**Issue by voidfire** [LaravelDaily/quickadmin#120]
I've followed http://laraveldaily.com/packages/quickadmin/#instdetailed
in a new laradock laravel 5.4 the installation went smoothly for the most part. 
On this part though.. Open CRUD creation form in route admin/menu/crud 
I get 
> 
> (1/1) ErrorExceptionUndefined property: stdClass::$column_name
> --
> in MySqlProcessor.php (line 16)
> 
Oh nevermind I just saw you closed a similar issue without providing any help as you discarded it as edge case scenerio. Too bad though the guys at laradock have done a great job to put toggether such an amazing stack.

Also I don't think its an edge case scenerio since I'm only using the basic mysql nginx workspace containers and all other panels tried worked flawsesly

**Comment by LaravelDaily** [comment]
@voidfire yes we didn't fix it because no one on our team uses Laradock, and the whole package works ok on Homestead and XAMPP and all default setups from Digital Ocean / AWS etc.

So we assumed it was an issue with Laradock and not our package.

**Comment by voidfire** [comment]
I'm sorry for the attitude. it's only by luck that I checked the closed issues to find someone with the same getting nowhere.. ill investigate this issue further and report tonight  or else i'll proceed with homestead. 

EDIT: Actually *I did*
found this https://github.com/rainlab/builder-plugin/issues/161


changing this /vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php line: 16
   return $r->column_name;
to this
   return $r->COLUMN_NAME; 
Makes the view appear as it should.

**Comment by LaravelDaily** [comment]
@voidfire I'm not saying Laradock is bad, it's just maybe incompatible with our package, or maybe the issue is on our side but we're not going to invest time in this case, unfortunately, have other priorities at the moment.

And you're saying that capitalizing the property in *vendor* folder is a good solution? Sounds really strange to me.

**Comment by voidfire** [comment]
Not a good solution, but more insights to further investigate

**Comment by voidfire** [comment]
This (https://github.com/laurenkt/framework/commit/aaf81ecf2cbbe4cdb6a930750b585fe8053bfc7b) works as well.

> Changed the query found in Illuminate\Database\Schema\Grammars\MySqlGrammar@compileColumnListing:
> 
> select column_name from information_schema.columns ...
> ...to...
> 
> select column_name as `column_name` from information_schema.columns ...
