### ISSUE TITLE
can't find integer data type on Quick Admin

### ISSUE THREAD

**Issue by Ronfaronald** [LaravelDaily/quickadmin#125]
is there Integer data type integer data type on quick admin

**Comment by PovilasKorop** [comment]
@Ronfaronald no, we have "Number" type only in our full online version at www.quickadminpanel.com

**Comment by Ronfaronald** [comment]
does ENUM work the same as number

**Comment by PovilasKorop** [comment]
No, enum is a set of options, it's totally different: https://dev.mysql.com/doc/refman/5.7/en/enum.html

**Comment by Ronfaronald** [comment]
what option do i choose if i want to insert numbers

**Comment by PovilasKorop** [comment]
@Ronfaronald there's no specific option for that.
