### ISSUE TITLE
How to use quickadmin with users table renamed

### ISSUE THREAD

**Issue by SteelManITA** [LaravelDaily/quickadmin#127]
I renamed users to users_access, so quickadmin can't find users table.
I read the documentation, but there isn't a way to specify the new name when I run quickadmin:install?

My error:
Base table or view not found: 1146 Table 'database.users' doesn't exist

**Comment by PovilasKorop** [comment]
@SteelManITA no we don't have such function, sorry

**Comment by SteelManITA** [comment]
So I must call my authentication table "users" to use quickadmin?

**Comment by PovilasKorop** [comment]
@SteelManITA yes, exactly. And quickadmin works with NEW projects, with fresh laravel installation, if you already have a project with your tables it probably won't work at all.

**Comment by SteelManITA** [comment]
So if I want to use a different name for users table I should create a project with users table, install quickadmin and at last rename all "users" occurrences?

**Comment by PovilasKorop** [comment]
@SteelManITA if you want to use a different name for users table, quickadmin won't work for you.

**Comment by SteelManITA** [comment]
Ok, thank you for the timely reply!
