### ISSUE TITLE
Undefined method during quickadmin:install

### ISSUE THREAD

**Issue by cichowski** [LaravelDaily/quickadmin#13]
Command:
`php artisan quickadmin:install`

results with error:
`Call to undefined method Illuminate\Foundation\Application::bindShared()`

**More information:**
That happened on fresh laravel project.
laravel/framework version: 5.2.6
Laravel Installer version: 1.3.1

Full actions track:
`laravel new project`
`composer require laraveldaily/quickadmin`
added *Laraveldaily\Quickadmin\QuickadminServiceProvider::class*
`php artisan quickadmin:instal`
result:
`[Symfony\Component\Debug\Exception\FatalErrorException]
 Call to undefined method Illuminate\Foundation\Application::bindShared()`

**Comment by ModestasV** [comment]
Hello, we are aware of this issue and it's currently being fixed. In a short time we will launch version 1.0.0 of Quickadmin package with this bug fixed. In the main time you can use our dev-master version which already has a fix for 5.2 version.

Thank you

**Comment by ModestasV** [comment]
This issue is fixed with v1.0
