### ISSUE TITLE
Costum Controller

### ISSUE THREAD

**Issue by cangak** [LaravelDaily/quickadmin#14]
hi im new in framwork 
i need ti create new costum controller, and after i generate, it only generate defoult index, and i copy paste from create controller, and return **Route [admin.group.create] not defined. (View: **
how i add route in costum controller, since i look at route.php there is no route for CRUD contrioller have been create before,
thanks

**Comment by ModestasV** [comment]
Hello,
You should create your custom routes in a usual place: App\Routes.php. By default this file will override our custom routes file.

**Comment by cangak** [comment]
that solv the problem thanks, i just make sure, it not break the "rule" of quickadmin, since i really new in   framework.
