### ISSUE TITLE
Can I download archive with my panel code?

### ISSUE THREAD

**Issue by mixartemev** [LaravelDaily/quickadmin#141]
I've successfully installed this package, then I've created my crud menus, but what's next?
Can I download code archive with my panel by this package (as I do in your web version)?

**Comment by PovilasKorop** [comment]
@mixartemev this package was the first version of the generator, long before the web version. So all it does is actually generate the code for you, so check your Controllers/Models/views, they should be generated, you don't need to download anything.

**Comment by mixartemev** [comment]
Oh! I see:) Great, thanx!
