### ISSUE TITLE
After upgrade Laravel 9 Route not found, please confirm if QuickAdmin 2.0.0 can work with Laravel 9 

### ISSUE THREAD

**Issue by hassanphp** [LaravelDaily/quickadmin#147]
After upgrade Laravel 9 Route not found, please confirm if QuickAdmin 2.0.0 can work with Laravel 9

**Comment by PovilasKorop** [comment]
@hassanphp the first line from the readme file:

IMPORTANT: This package is not actively maintained and probably won't work with newest Laravel versions.
