### ISSUE TITLE
QuickadminMenuController.php line 343: Undefined index: parent_id

### ISSUE THREAD

**Issue by cangak** [LaravelDaily/quickadmin#15]
hello there,
i try to edit menu that have no parent, or this menu as parent it return
`QuickadminMenuController.php line 343: Undefined index: parent_id`
i think a little bug here
i change
` if ($requestArray['parent_id'] === "null") {
            $requestArray['parent_id'] = null;
        }`
into
`if (!isset($requestArray['parent_id'])) {

            $requestArray['parent_id'] = null;
        }`

couse 
dd($requestArray);
there is no key [parent_id];
so i change to isset instead of === 'null'

thanks

**Comment by ModestasV** [comment]
Hello,
Thanks for contacting us, we will look into this bug a bit later today. In the mean time, you can feel free to contribute and submit your solution as a contributor!

**Comment by ModestasV** [comment]
Reopening issue because it was not solved from our side

**Comment by ModestasV** [comment]
This issue should be solved
