### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by tpharaoh** [LaravelDaily/quickadmin#18]
Uploading file I get:

FileNotFoundException in File.php line 37:
The file "/tmp/phpUu3Bhl" does not exist

Is that because I am using php artisan serve in development?

**Comment by ModestasV** [comment]
Hello @tpharaoh ,

Could you tell what are you trying to do? Seems that this error is not from our package but rather from your configuration. If that's the case - we are unable to help you.

**Comment by tpharaoh** [comment]
Simply put I used quick admin to make a file upload. Uploaded a CSV.

It is possible the error is because I am using php artisan serve, so then you are right it's not you.

**Comment by tpharaoh** [comment]
I did some more testing... and I think it must be part of quick admin.
$this->saveFiles($request); this line works, but it returns the error I previously mentioned.

The file does save... but then stops

**Comment by tpharaoh** [comment]
I know this is not the right way to code it, but in testing, I got it to work doing it this way:
`		foreach ($request->all() as $key => $value) {
			if ($request->hasFile($key)) {
				$filename = time() . '-' . $request->file($key)->getClientOriginalName();
				$request->file($key)->move(public_path('uploads'), $filename);
				Filetypeagain::create([$key=>$filename]);

			}
		}
		return redirect()->route('admin.mynewpage.index');
`

**Comment by w00p** [comment]
Hi,

I am getting the same error when i am trying to upload a picture or file, this is what is posts in my DB:
`/tmp/phpX46XKV`

All the files is correctly uploaded to /public/uploads/ and /public/uploads/thumb/

Its a brand new laravel installation, v5.2.21, and quickadmin.

**Comment by tpharaoh** [comment]
The solution I posted worked for me

**Comment by w00p** [comment]
I what file did you put the code?

**Comment by tpharaoh** [comment]
I am not near my dev PC now, but I put it in the file you have in the "use" on top of the automatically generated CRUD controller.

**Comment by ModestasV** [comment]
Will investigate this issue in few days

**Comment by tomhatzer** [comment]
@tpharaoh Can you please try and remove this marked line from the file and see, if you still receive the error?

https://github.com/LaravelDaily/quickadmin/blob/b17740fd85628b402176bcb9f501f840a65b40d4/src/Controllers/publish/FileUploadTrait#L45 (src/Controllers/publish/FileUploadTrait.php - Line 45)

The uploaded file is getting moved 2 lines before and isn't available at this line anymore. So it's throwing an error.

**Comment by tpharaoh** [comment]
No, didn't seem to help for me.

I also tried removing the similar line on line 40.

I checked my other quick admin install where I have it working, and in that
one I specifically put the code in the Controller itself as so:


foreach ($request->all() as $key => $value) {
if ($request->hasFile($key)) {
$filename = time() . '-' . $request->file($key)->getClientOriginalName();
$request->file($key)->move(public_path('uploads'), $filename);
Controllername::create([$key=>$filename]);
}
}

**Comment by tomhatzer** [comment]
Ok and you only get this error when uploading a CSV file, right?

**Comment by tpharaoh** [comment]
no, also jpg

**Comment by tomhatzer** [comment]
@tpharaoh what version of laravel are you using currently?

**Comment by tpharaoh** [comment]
5.2.16

**Comment by tomhatzer** [comment]
Ok I think the problem is somewhere else... Based on this issue created at the laravel repo, it could be a laravel problem I think.

Have a look here: https://github.com/laravel/framework/issues/12350

They tell them to upgrade laravel to a newer version. Could you try this too and see if it helps?

**Comment by tpharaoh** [comment]
OK, I guess I follow up there....

Now I get the same error someone in that threat mentioned, that the saved
file is the /tmp/phpTzUONP name

But, I will follow that thread now looking...
