### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by twoSeats** [LaravelDaily/quickadmin#24]
Currently namespaces are hard coded all over the source.

To allow more flexibility for developers; can changes be made to make use of [AppNamespaceDetectorTrait](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Console/AppNamespaceDetectorTrait.php) perhaps?

This would allow developers more control of their code instead of being locked into the "App" namespace which is hardcoded into the use statements of files like [QuickAdminController](https://github.com/LaravelDaily/quickadmin/blob/master/src/Controllers/QuickadminController.php) & the files within [Builders](https://github.com/LaravelDaily/quickadmin/tree/master/src/Builders)

**Comment by LaravelDaily** [comment]
Hi @twoSeats - thank you for the comment. Good suggestion probably, but it would make the app more complicated for Laravel starters who don't play too much with traits and then would get lost in namespaces. You can make a fork, I guess, and make this change for your needs.
