### ISSUE TITLE
Update my local dev environment with branch master

### ISSUE THREAD

**Issue by DigitalCoder** [LaravelDaily/quickadmin#27]
Hi ! all

I have a silly question to ask ^^

I've installed since last week and yesterday a new project using quickadmin by Installing the package via `composer require laraveldaily/quickadmin`

And add watching option to be notified of all conversation.

Then I've seen thats there was updates since 3 days from Fixed issue #15

I'd like to know what is the best way to retrieve the last modification from the master and update my laravel project without having to report each modification.

May be clone from https://github.com/LaravelDaily/quickadmin.git or download zip and simply past quickadmin source and then copy past in vendor/laraveldaily/quickadmin ?
will I need to execute again `php artisan quickadmin:install` ?

**Commits** on Mar 1, 2016
> @LaravelDaily
> Merge pull request #25 from twoSeats/twoSeats-patch-1  …
> LaravelDaily committed 18 hours ago
> cf8a6aa  

> @LaravelDaily
> Merge pull request #26 from justutiz/master  …
> LaravelDaily committed 20 hours ago
> 376e654  

> @justutiz
> Fixed issue #18
> justutiz committed 20 hours ago
> e7f8129  

**Commits** on Feb 28, 2016

> @twoSeats
> Update 2015_10_10_000000_create_menus_table  …
> twoSeats committed 3 days ago

**Comment by LaravelDaily** [comment]
Hi @DigitalCoder - thanks for the question. I've just released a new stable version with latest fixes, so you can do composer require easily.

**Comment by DigitalCoder** [comment]
Thx !
