### ISSUE TITLE
Error when creating new Crud

### ISSUE THREAD

**Issue by DigitalCoder** [LaravelDaily/quickadmin#30]
Every time I try to create a new Crud

For example :
- CRUD name : categories
- CRUD Title : Categories
- Roles (checked) : Administrator
- Use soft delete? = Yes
...
and Add fields

It should create : 
- 2016_03_03_133112_create_categories_table.php 
but it create :
- 2016_03_03_133112_create_roles_table.php

and after It give me SQL errors :
QueryException in Connection.php line 669:
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' (SQL: create table `roles`

I've put a debug (with debugbar) in vendor/laraveldaily/quickadmin/src/Builders/MigrationBuilder.php and I've got this :
`-- migration builder ---`
`$this->name : roles`
`$this->fileName : 2016_03_03_133112_create_roles_table.php`
`$this->className : CreateRolesTable`

It should be :
`-- migration builder ---`
`$this->name : categories`
`$this->fileName : 2016_03_03_133112_create_categories_table.php`
`$this->className : CreateCategoriesTable`

I don't understand why

**Comment by DigitalCoder** [comment]
In fact after macro debugging

I've seen that this file is not updated storage/framework/cache/fieldsinfo

**Comment by DigitalCoder** [comment]
in fact, I had to have a mistake at some point.
after which the cache file "fieldsinfo" had not been removed via $ cache-> destroy ('fieldsinfo');

I therefore added to the beginning of the `public function createCrud function ()` in **vendor/laraveldaily/quickadmin/src/Builders/ControllerBuilder.php**, this to be sure :
```
// Init QuickCache
        $cache                   = new QuickCache();
        // Destroy our cache file
        $cache->destroy('fieldsinfo');
```

If you have a better solution ?

Thx

**Comment by LaravelDaily** [comment]
@DigitalCoder it seems like something on your side with caching, we didn't encounter it within our team while using QuickAdmin. So there's no better solution at the moment, closing the issue.
