### ISSUE TITLE
bootstrap-datepicker.standalone.min.css

### ISSUE THREAD

**Issue by DigitalCoder** [LaravelDaily/quickadmin#31]
in **quickadmin/src/Views/admin/partials/header.blade.php**
do you really need :
`<link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.standalone.min.css"/>`

???

**Comment by ModestasV** [comment]
I don't see where the problem is. We have a datepicker field and its library, or am I missing something?

**Comment by DigitalCoder** [comment]
I'm wondering why loading these css ?
because the javascript library https://github.com/eternicode/bootstrap-datepicker is not used

The library used for date time picker is :

```
<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script src="http://localhost:8001/quickadmin/js/timepicker.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.js"></script>
```

and it use jquery ui css theme :

`<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">`

**Comment by ModestasV** [comment]
Well, as far as I can see - you are asking about datepicker and showing us timepicker. These are two different plugins :)

**Comment by DigitalCoder** [comment]
I've tried to create a crud with a field date picker and a field date and time picker
![capture d ecran 2016-03-09 a 16 28 38](https://cloud.githubusercontent.com/assets/1869232/13640285/49a986c2-e614-11e5-90f1-eb9dd1474298.png)
![capture d ecran 2016-03-09 a 16 28 44](https://cloud.githubusercontent.com/assets/1869232/13640286/49ab11b8-e614-11e5-9259-e1c854a02955.png)


and twice only use timepicker (jquery ui)
and never bootstrap-datepicker (https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js)

I think I will change after for https://github.com/Eonasdan/bootstrap-datetimepicker
which is compatible bootstap v3.3.6.
And I will remove :
- jquery-ui.min.js javascript library and css smoothness/jquery-ui.css
- timepicker.js
- jquery-ui-timepicker-addon
- bootstrap-datepicker.standalone.min.css

and I will only load :
- resources/assets/vendor/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css
- resources/assets/vendor/bootstrap-datepicker-dist/js/bootstrap-datepicker.min.js

**Comment by ModestasV** [comment]
Hello,
If you could do a pull request with your modified file - it would be great. At this point we are more focused on some other features
