### ISSUE TITLE
little mistake in the syntax Templates fields radio

### ISSUE THREAD

**Issue by DigitalCoder** [LaravelDaily/quickadmin#32]
I've created new crud with radio field and when loading the view I have an error :

> Use of undefined constant optin1 - assumed 'optin1' (View: 

generated code :
`<div class="form-group">
        {!! Form::label('radio1', 'optin 1', array('class'=>'col-md-2 control-label')) !!}
        <div class="col-sm-10">
            {!! Form::radio('radio1', optin1, false) !!}
        </div>
    </div>`

in **vendor/laraveldaily/quickadmin/src/Templates/fields/radio**

a little mistake in the syntax ?
`{!! Form::radio('$LABEL$'$VALUE$, false) !!}`

It should be this, non ?
{!! Form::radio('$LABEL$', '$VALUE$', false) !!}

to have : `Form::radio('name', 'value', false);`

Thx

**Comment by ModestasV** [comment]
Thanks for this report, issue should be fixed now :)
