### ISSUE TITLE
Menu add more subcat ...

### ISSUE THREAD

**Issue by DigitalCoder** [LaravelDaily/quickadmin#35]
currently we have :

** Category > (menu_type = 2 & parent_id = NULL)
- link (menu_type = 1 & parent_id = 3)
- link (menu_type = 1 & parent_id = 3)

do you think we could have :
** Category > (menu_type = 2 & parent_id = NULL)
* SubCategory > (menu_type = 2 & parent_id = 3)
- link (menu_type = 1 & parent_id = 4)
- link (menu_type = 1 & parent_id = 4)

etc ... whatever

**Comment by LaravelDaily** [comment]
Thank you for suggestion, but we are not planning to make more than two-level menus at the moment.

**Comment by DigitalCoder** [comment]
All right !

If I have the time I will do it and share it after ^^
