### ISSUE TITLE
New menus do not appear after creation

### ISSUE THREAD

**Issue by ykonijn** [LaravelDaily/quickadmin#39]
I installed on a clean version of Laravel 5.2 and everything seems to be working. I create a new menu and all the DB tables are updated, a controller is created and everything seems to be working. However no new menu is created on the side bar. Also, any item below the parent menu is inaccessible to me. 

Attached screen shot: there should be another menu below the Database Structure menu
![capture](https://cloud.githubusercontent.com/assets/7234654/13945937/f109a8b6-f019-11e5-8e90-b75ba65b57e8.PNG)

**Comment by ModestasV** [comment]
Hello, thank you for this report, will check this as soon as possible

**Comment by ModestasV** [comment]
Issue should be solved. If you have generated CRUD and it didn't appear - please check that your parent id is correct.

Have a nice day!
