### ISSUE TITLE
Class 'App\Users' not found when using relationship

### ISSUE THREAD

**Issue by w00p** [LaravelDaily/quickadmin#4]
After making a new CRUD with relationship User -> UserS -> id i get following error:
```Class 'App\Users' not found```

I think it should be *User* not *Users*, am i correct?

**Comment by ModestasV** [comment]
Hello,
Yes you are correct. This should be fixed in the main creating of the CRUD Users with `is_crud = 0`

**Comment by ModestasV** [comment]
Hello @w00p,
We would like if you could confirm that this bug is fixed with our new dev-master version of this package

**Comment by w00p** [comment]
Thank you, its now OK :)
But i had to manualy add 777 persmission to resources/views/admin, or els i got an persmission error.
