### ISSUE TITLE
User Account

### ISSUE THREAD

**Issue by unixtime** [LaravelDaily/quickadmin#40]
- When I change the user role, user no longer can login. The password I guess it default to blank.
- Also when you click on modify user, the user default role always shows as admin, it does not reflects the correct role.
- Please upgrade datatables-oracle to 6.0
- The radio and checkbox fields in the crud design page does not allow to have multiple entries or I guess I am not sure how to add multiple checkboxes or multiple radio buttons in the same group. For example in html form a typical group:
```
<label for="checkbox_0" class="checkbox-inline">
        <input name="checkbox_[]" id="checkbox_0" value="Email" checked="" type="checkbox"> Email </label>
        <label for="checkbox_1" class="checkbox-inline">
        <input name="checkbox_[]" id="checkbox_1" value="Phone" type="checkbox"> Phone </label>
        <label for="checkbox_2" class="checkbox-inline">
        <input name="checkbox_[]" id="checkbox_2" value="Mobile" type="checkbox"> Mobile </label>
```
- Reordering the menu makes the sub menu and the crud disappear. Also when editing the sub menu default back to no parent menu.
- Thank you for making this package, it saved me hours.

**Comment by ModestasV** [comment]
Hello,
Sorry for this long waited reply but here's few answers:
1. We will look into that. Probably it is a case of dual hashing a password.
2. We will look into that.
3. Upgrading
4. Yes, at this point you can't create form groups.
5. We will look into that.

**Comment by ModestasV** [comment]
Hello again, most of the problems should be fixed with latest commits

**Comment by unixtime** [comment]
Awesome!! Thank you very much!
