### ISSUE TITLE
Problem with Yajra Datatables?

### ISSUE THREAD

**Issue by richoid** [LaravelDaily/quickadmin#41]
I'm getting "[Symfony\Component\Debug\Exception\FatalErrorException]       
  Class 'yajra\Datatables\DatatablesServiceProvider' not found"

I could make the error go away by specifying 5 instead of 6 in composer:
"yajra/laravel-datatables-oracle": "~6.0"

Also, under /admin/menu/custom it looks like:
quickadmin::qa.menus-createCustom-create_new_custom_controller

This pattern appears throughout... Related? Did I miss a step when I installed?

Thanks!

**Comment by ModestasV** [comment]
Hello,
Sorry for this problem, somehow the package was initialized with lowercase letter at the beginning..
As for the second one, it could be due the fact that the installation was not a success and the system didn't copy the files to your installation. Please try to reinstall this package and tell me if the problem persists.

Have a nice day!
