### ISSUE TITLE
issue when creating new Crud  Page blank

### ISSUE THREAD

**Issue by sshekhawat** [LaravelDaily/quickadmin#42]
I try to create a new Crud then after save button click page blank 
In menu table data insert properly but not create new table for new menu 
I don't understand why  and I am using  laravel 5.2

**Comment by ModestasV** [comment]
Hello,
Could you give us more details? I can't recreate this error

**Comment by sshekhawat** [comment]
I go to menu and click "Create new CRUD Controller"  When i Create new CRUD menu item  then i got issue 

FatalErrorException in 2016_04_06_134513_create_page_table.php line 0: Cannot redeclare class CreatePageTable

This file location is /var/www/html/meridian/database/migrations   and 
new file permission is 
Owner : www-data
Group : www-data
   access : " read only "
Other    "read only "

And i check database i don't find new table for new crud menu item

**Comment by ModestasV** [comment]
I guess the problem is that you tried to create a CRUD and it failed or that you creating the same crud twice. The error you have is mostly caused by the fact that the system is trying to create a second class named identically.

The one thing that I can offer is try to delete the half generated files and delete our cache file located in storage folder.

**Comment by sshekhawat** [comment]
Thanks for raply 
Now i get this error , can u help me for it 
ErrorException in /var/www/html/meridian/vendor/laraveldaily/quickadmin/src/Builders/ViewsBuilder.php line 288:
chmod(): Operation not permitted

**Comment by ModestasV** [comment]
This is the result of user rights not used right. To be fair I can't help you with that more than offer you to check your right with which apache is runnig :)

**Comment by DigitalCoder** [comment]
maybe the same pb [https://github.com/LaravelDaily/quickadmin/issues/30]

- remove the data entries in database Table: menus for "CreatePage"
- delete file "fieldsinfo" from cache directory
- if it exists remove migration file 2016_04_06_134513_create_page_table.php 
- search everyWhere in your project directory the occurrence or files "CreatePage"

And let's try again ^^

Regards
