### ISSUE TITLE
Datatables issue again?

### ISSUE THREAD

**Issue by ergonomicus** [LaravelDaily/quickadmin#43]
First I did a composer update to some older installation, and noticed that server is returning 500 in 'user actions' view. Then I've tried with fresh installation and same thing happened. I got "Fatal error: Class 'yajra\Datatables\Datatables' not found." message.

I managed to resolve this just by changing "use yajra\Datatables\Datatables;" to "use Yajra\Datatables\Datatables;" (with capital Y in word Yajra!) in vendor/laraveldaily/quickadmin/src/Controllers/UserActionsController.php file.

You probably know this already, but I think it should be fixed...

Nice package, BTW :-)

**Comment by ModestasV** [comment]
Hello,
This problem is solved with our latest version if QuickAdmin.

**Comment by ergonomicus** [comment]
I was talking about latest version... Search everything for 'yajra' and replace it with 'Yajra' namespace.

**Comment by ModestasV** [comment]
@ergonomicus Then it is possible that i didn't understand you quite well... Sorry for that and I'm going to check it as fast as possible

**Comment by ModestasV** [comment]
Sorry for this really long wait, with dev-master it should work fine now and we will be releasing updated package version soon
