### ISSUE TITLE
Neprivalomas "datapicker" laukelis sukelia Exception'ą.

### ISSUE THREAD

**Issue by ArturSubotkevic** [LaravelDaily/quickadmin#44]
Sugeneravus naują CRUD su neprivalomu laukeliu **datapicker** - sukūrimo/redagavimo formose laukelio numatytoji reikšmė yra nenustatyta (tuščia). 

Tokiu atveju, išsaugant įrašą su neįvesta reiškme į **datepicker** laukelį mums grąžina klaidą:
> **InvalidArgumentException in** Carbon.php line 425:
> **Data missing**

**Priežastis modelyje:**
`public function setBirthdayAttribute($input)
    {
        $this->attributes['birthday'] = Carbon::createFromFormat(config('quickadmin.date_format'), $input)->format('Y-m-d');
    }`

`public function getBirthdayAttribute($input)
    {
        return Carbon::createFromFormat('Y-m-d', $input)->format(config('quickadmin.date_format'));
    }`

Klaidos atveju **$input** yra tuščias, todėl mums grąžina **InvalidArgumentException**.

### Reikėtų nuspręsti
Ar generuoti _view_ failą su nustatyta pagal nutylėjimą reikšme be galimybės jos pašalinti.
Ar racionaliau aprašyti generuojamo _model_ funkcijas.

**Comment by ModestasV** [comment]
Labas,
Su dev-master versija šios problemos nebeturėtų būti.
