### ISSUE TITLE
Checkbox neužsideda "checked"

### ISSUE THREAD

**Issue by MantasJa** [LaravelDaily/quickadmin#45]
ant active checkbox input`o neužsideda "checked"

vendor/laraveldaily/quickadmin/src/Templates/fields/checkbox:5

```
        {!! Form::checkbox('$LABEL$', 1, $STATE$) !!}
```

**Comment by ModestasV** [comment]
Labas,
Teisingas pastebėjimas - turėdami laisvesnio laiko sutvarkysime. Ačiū

In english:
There is a bug where checkbox is not setting it's state in edit form. We will look into that when we will have more time. Sorry for this
