### ISSUE TITLE
Not able to create new CRUD controller, parent menu and custom controller

### ISSUE THREAD

**Issue by swetashukla16** [LaravelDaily/quickadmin#46]
I just set up new quickadmin panel in my project. Logged in and tried to create new CRUD controller, Parent Menu and Custom controller but not able to create any of these three.

I am getting errors as mentioned below. 

FatalErrorException in AliasLoader.php line 63:
Maximum function nesting level of '100' reached, aborting!

FatalErrorException in helpers.php line 839:
Maximum function nesting level of '100' reached, aborting!

The entry is shown in database "menus" table like: 

Position: 0
menu_type: 1
icon: fa-database
name: Pages
title: Pages
parent_id: NULL
created_at: 2016-04-14 12:55:24
updated_at: 2016-04-14 12:55:24

When I delete this entry directly from the database then the error in admin panel disappears but when again i tried to create, i got same errors. Please help me.

**Comment by ModestasV** [comment]
Hello,
This error is caused by your php configuration and not by our package. 

Please look at the following link or try to search for you error in google (it is a common error with laravel and xdebug): http://stackoverflow.com/questions/8656089/solution-for-fatal-error-maximum-function-nesting-level-of-100-reached-abor

**Comment by swetashukla16** [comment]
I already tried the solution given by you before posting this issue but no outcome. Is there any other solution for this??

**Comment by ModestasV** [comment]
If it didn't give any result - you are doing it wrong. Try to re-check your configuration files and settings. From this point we can't really help you because it's a problem of machine configuration
