### ISSUE TITLE
custom function 

### ISSUE THREAD

**Issue by sshekhawat** [LaravelDaily/quickadmin#47]
I have Create new CRUD Controller  and its working fine 

Now i create new function getCsv  in controller   app/Http/Controllers/Admin/NewsletterController.php
my issue i can't get this function value 

i have also define the path in routes.php
Route::get('csv', array('as' => 'csv', 'uses' => 'NewsletterController@importExport'));

My Browser url is 
localhost/html/sitename/public/admin/newsletter/csv

**Comment by ModestasV** [comment]
Hello,
Thanks for this report. Something have messed up in route ordering. Will check as soon as we have a bit more free time.

**Comment by ModestasV** [comment]
@sshekhawat Hello again, please read our updated readme file and move our service provider below your RouteServiceProvider. This will fix your problem

**Comment by sshekhawat** [comment]
Thanks For Quick Reply. And Quickadmin is awesome ,amazing 
I am make first time in laravel. Can u tell me how to use easily in forn-end .

**Comment by Abubaker87** [comment]
I am creating a new method in a controller generated by QuickAdmin Panel. When I am trying to access that route with URL it cannot find that route. Am I missing any step?

**Comment by ModestasV** [comment]
@Abubaker87 Yes, you need to add new routes too, not just a method in controller. https://laravel.com/docs/5.3/routing#basic-routing
