### ISSUE TITLE
Problem with Required field and Request after using relationship with ID

### ISSUE THREAD

**Issue by w00p** [LaravelDaily/quickadmin#5]
After making a CRUD with relationship, and making it required. 
img: http://imgur.com/SxwawHm

This is the generated Request file, the id field show only a -
```
	public function rules()
	{
		return [
            'title' => 'required', 
            '-' => 'required', 
            
		];
	}
```

Am i making the CRUD wrong, or is there an error?

**Comment by ModestasV** [comment]
Hello,
Thank you for the report - I will investigate it.

**Comment by ModestasV** [comment]
Hello @w00p,
Could you install our latest dev-master package version and confirm that this issue is no longer there?

**Comment by w00p** [comment]
Thank you, its now ok :)
