### ISSUE TITLE
Daugiau negu vienas paveiksliukas neišsisaugo

### ISSUE THREAD

**Issue by grambas** [LaravelDaily/quickadmin#50]
Traits/FileUploadTrait.php

if ($request->hasFile($key)) 

if  neveikia, nes antram failui grąžinama false ir jis praleidžiamas

Bugas laravel git'e
https://github.com/laravel/framework/issues/2441

**Comment by ModestasV** [comment]
This bug is caused by Laravel core and not by our package. It was working fine when we added it.
