### ISSUE TITLE
suggestion: secure_asset vs url

### ISSUE THREAD

**Issue by tpharaoh** [LaravelDaily/quickadmin#54]
I was using an SSL site, and browser would not load the CSS.

Modified header.blade.php as follows:
    <link rel="stylesheet"
          href="{{secure_asset('quickadmin/css') }}/font-awesome.min.css"/>

**Comment by ModestasV** [comment]
Hello, 
It is not an issue, it is a use case with encryption so in therefore we cannot add it due to possible errors to those without ssl.
