### ISSUE TITLE
How to delete controller or menu?

### ISSUE THREAD

**Issue by foRsxs** [LaravelDaily/quickadmin#58]
Hi, thanks for your job. Its very simple and usefull for back-end.

I don't know how to delete controller or menut item? Is exists any way to do this like Add Controller or i need to delete controller from filesystem?

Also, if i want to create DB table with name like this (type_products), its possible? Now i change name DB and correct $table in model

and last question - If i want to correct of added DB table, i cant to do migrate:rollback (error Class `CreateNameContoller` not found. So how i can to do something like add new column

**Comment by vsouto** [comment]
As long as i can tell, you have to delete the entry in the database table "menus", and delete the files created:
- app/controllers/admin/yourEntity
- app/requests/yourEntity
- resources/views/yourEntity

**Comment by foRsxs** [comment]
Thanks for your answer! 

How i can to create custom DB name like this (type_products)

**Comment by ModestasV** [comment]
At this point with this package you need to manually delete all files from your system.
