### ISSUE TITLE
Permission issue on resources/views/admin

### ISSUE THREAD

**Issue by ModestasV** [LaravelDaily/quickadmin#6]
Hello,
Currently we are investigating an issue where `resources/views/admin` is not writable.

Issue reported by: @w00p

**Comment by w00p** [comment]
I also noticed that all files made by Quickadmin from CRUD, is with the www-data user and not the user owning the files. So the owner permissions of files is wrong.

See example picture: http://imgur.com/rol9uzd

**Comment by ModestasV** [comment]
@w00p 
I investigated the case and I can tell you this:
We are going to set `resource/views/admin` directory to writable in case of permission issue.

For the www-data user, this is ok because php must access these files. If you set them otherwise - we will have more conflicts.

Tell me if I'm wrong but most people say that it is ok.

**Comment by ModestasV** [comment]
This issue should be fixed with @dev-master. 

Can anyone confirm?
