### ISSUE TITLE
How to use separate controllers?

### ISSUE THREAD

**Issue by vsouto** [LaravelDaily/quickadmin#60]
I must be crazy or doing something wrong.

How come my quickadmin dont use /admin routes?

I mean, i enter quickadmin panel through /admin, but then all links in the menu points to /users or something always without the /admin prefix...? So all the routes are overwriting my default routes on my project?

Is there an easy way to put all quickadmin routes within the "admin" prefix, so it doesnt mess up my default routes?

**Comment by ModestasV** [comment]
Sorry for long waiting time.

There is an option in config file to do so: 
We are using this to prefix our routes:
`  'prefix'     => config('quickadmin.route'),`
