### ISSUE TITLE
Access controller with parent menu

### ISSUE THREAD

**Issue by feber** [LaravelDaily/quickadmin#62]
I have custom CustomerController, which is submernu of Location menu.
When I try to access it:
``` php
NotFoundHttpException in Handler.php line 103:
No query results for model [Laraveldaily\Quickadmin\Models\Menu].
```
Any lead which I can follow?
Thanks.

**Comment by ModestasV** [comment]
Hello,

This might be due the case that your model was not generated. At this point we can't help you a lot due the fact that there is a lot of different cases that might happen.
