### ISSUE TITLE
File upload does not accept file

### ISSUE THREAD

**Issue by jhayarevalo** [LaravelDaily/quickadmin#63]
Hi, I'm having a problem with uploading particular files with the admin panel in a file field. Some files work while others do not. This particular file upload field is required for a controller I have created and I have set the size limit to 15mb. I am trying to upload a pdf file which is just under 7mb, but when I try to create the entry, it returns the error at the top that the field is required, and the file field shows no file selected. 

Is there other restrictions that do not allow me to add certain files or what do you think may be causing this issue?

**Comment by ModestasV** [comment]
Hello,

Sometimes there is a bug when uploading more than one file would crash Laravel file upload script. We are working to fix this case inside our team projects but we don't have any results yet...
