### ISSUE TITLE
How to manage n to n relationship?

### ISSUE THREAD

**Issue by heimasi** [LaravelDaily/quickadmin#65]
How to manage n to n relationship with quickadmin gui?

**Comment by vsouto** [comment]
What you mean? In terms of what? Please elaborate your question.

**Comment by ModestasV** [comment]
Hello,

It is not currently possible to make many to many relationships. At this point it is only possible to make `belongsTo` relationship.

**Comment by vsouto** [comment]
I dont see how any relationship is impossible. You just update your model, your views, and done. Whats the secret?

**Comment by ModestasV** [comment]
@vsouto The problem is that heimasi wants to use graphical interface which does not allow for such relationships. But if you are willing to edit files - there is no restrictions to that

**Comment by vsouto** [comment]
I see. Yeah, in that case you are extremely limited.
