### ISSUE TITLE
Uppercase letter and underscore in CRUD name and table name issue

### ISSUE THREAD

**Issue by arifrifai** [LaravelDaily/quickadmin#66]
Cannot use underscore or uppercase letter in CRUD name using sqlite database.

Error:
NotFoundHttpException in Handler.php line 103:
No query results for model [Laraveldaily\Quickadmin\Models\Menu].

ModelNotFoundException in Builder.php line 303:
No query results for model [Laraveldaily\Quickadmin\Models\Menu].

**Comment by LaravelDaily** [comment]
Thank you for the issue report, we currently don't support sqlite database and package wasn't tested for it.
