### ISSUE TITLE
Overwrote current login system

### ISSUE THREAD

**Issue by thedangler** [LaravelDaily/quickadmin#67]
I already had a way for users to log into their account using /login using auth/login
How would I go about changing your code to use a different route like admin/login, admin/logout

I found the routes.php file in the vendor folder, im just not sure where I would override it.

Matt

**Comment by ModestasV** [comment]
Hello,
Our routes should get overwritten by your routes.php file. For example: if we have a route that is /login and you specify in your routes file that /login redirects to /auth/login and it shows the form - it should work. If it doesn't then there is only two options left: Fork the package and adapt it to your needs or leave it as is...

Please tell us what have you tried and what worked best for you!
