### ISSUE TITLE
How can i edit a created CRUD Controller?

### ISSUE THREAD

**Issue by orkunsenturk** [LaravelDaily/quickadmin#69]

**Comment by ModestasV** [comment]
Hello @orkunsenturk, Could you provide a description to your issue?

**Comment by orkunsenturk** [comment]
Hi,
For example, i created a new crud controller named 'Campaings', and then added 2 fields with names 'Campaign Name' and 'Campaign Date' and created the CRUD.

Then i realized that i need to add a 3rd field with name 'Campaign Description'. What steps i should take to add this field?

Thank you.

**Comment by bencyn** [comment]
its either you recreate the crud or add the new description snippet to each file starting from the controllers,requests,model down to the resources views. which includes create edit and index.blade.

**Comment by ModestasV** [comment]
At this point this package does not support editing of already existing CRUD. For this - please reffer to our online version at: http://www.quickadminpanel.com - there you will be able to add or remove fields from your CRUD.
