### ISSUE TITLE
Reloading migrations lose roles and admin users - seeds needed

### ISSUE THREAD

**Issue by skattabrain** [LaravelDaily/quickadmin#7]
Seems to me that the quickadmin:install should create a seed file in addition to creating the user and roles, otherwise the user is lost (while all the crud files are still present and set up). I often run migrations from scratch as part of my development process. 

Seems like you would need seed files for cruds as well.

**Comment by ModestasV** [comment]
Hello,
Thank you for your feedback. We will look into it.

**Comment by PovilasKorop** [comment]
Thank you for the feedback @skattabrain - both here and on the LaravelDaily blog. See, QuickAdmin in this version is not suitable for re-generation, it's more for a quick start and then editing the files manually after that. So at this point we will leave this idea for future versions.
