### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by M0H3N** [LaravelDaily/quickadmin#71]
Hi 
After installing the package .... I created new CRUD controller ... but I got this error : 

`Route [admin.product.index] not defined. (View: D:\QuickAdmin\resources\views\admin\partials\sidebar.blade.php) (View: D:\QuickAdmin\resources\views\admin\partials\sidebar.blade.php) (View: D:\QuickAdmin\resources\views\admin\partials\sidebar.blade.php)`

what is the problem ?

**Comment by ModestasV** [comment]
Hello,

Thanks for reporting this issue. We will check this error as soon as we can. While waiting - open sidebar.php file and check if routes are asked correctly.

This problems is caused due to the new Laravel way of getting route names
