### ISSUE TITLE
product CRUD problem

### ISSUE THREAD

**Issue by M0H3N** [LaravelDaily/quickadmin#72]
Hello
I installed the package and it works  properly but only when I create new CRUD menu item with 
`CRUD name : product`   this error happens :
`Parse error: syntax error, unexpected 'db' (T_STRING), expecting ',' or ')' (View: D:\L5.3\resources\views\admin\product\index.blade.php)`

**Comment by ModestasV** [comment]
Will investigate what went wrong. Thanks!

**Comment by LaravelDaily** [comment]
@M0H3N could you attach or send us (info@laraveldaily.com) that product/index.blade.php file

**Comment by ModestasV** [comment]
Closing this issue. We could not find a reason to what went wrong.
