### ISSUE TITLE
Class role does not exist

### ISSUE THREAD

**Issue by nexxai** [LaravelDaily/quickadmin#74]
I just setup a new project and I'm getting this error message after logging into /admin and choosing any of the options on the left hand panel:

```
ReflectionException in Container.php line 734:
Class role does not exist
```

As far as I can tell the RolesController.php and Role.php files exist in the correct place but that's about as far as I'm able to get.

**Comment by LaravelDaily** [comment]
Hi @nexxai 
You probably missed one of our installation points:
5. Register middleware 'role' => \Laraveldaily\Quickadmin\Middleware\HasPermissions::class, in your App\Http\Kernel.php at $routeMiddleware
