### ISSUE TITLE
After creating CRUD - exception from Menu model

### ISSUE THREAD

**Issue by index-panayotov** [LaravelDaily/quickadmin#78]
Hello,

I found a problem, that I can not understand why it's happens.

I'm creating "Blog Category" under "Blog" parent menu with name "blog_category".
It's creates migration, view, model and controller. But when I try to reach it  via admin panel I'm getting error  twice a page.

> No query results for model [Laraveldaily\Quickadmin\Models\Menu].

Can not find the problem. Here is a record from menus table 

> 4	0	1	fa-database	BlogCategory	Blog Category		2016-10-07 07:35:30	2016-10-07 07:35:30

**Comment by ModestasV** [comment]
Hello,
Thank you for reporting this bug, we will check what could go wrong there! 
In the meantime we suggest you giving a try to our online version: www.quickadminpanel.com

**Comment by PovilasKorop** [comment]
Hi Preslav,
Unfortunately, I don't think we can debug/fix the error without having your project/database, so what I would suggest is to debug it yourself locally, and if you see that there is a bug somewhere in the generator, please let us know and we will fix it.

**Comment by index-panayotov** [comment]
Hello @PovilasKorop,
I created a few more projects with empty databases and I get the same error

**Comment by PovilasKorop** [comment]
Hi @index-panayotov - as I said, without your help with debugging locally, we cannot help you. We don't know which Menu item isn't found on your side. If you debug it and tell more details, then we can fix the issue on our end, but for now - don't know what to fix, sorry.
