### ISSUE TITLE
CRUD Update Error

### ISSUE THREAD

**Issue by jzmwebdevelopment** [LaravelDaily/quickadmin#79]
When I go to update my CRUD.  I have a required text field because it needs a name - However I am getting " The name has already been taken. " on /1/edit on page update

**Comment by PovilasKorop** [comment]
Please check your Request files - that error says that field "name" is marked as "unique". If it shouldn't be unique, remove that validation rule in Request file.

**Comment by jzmwebdevelopment** [comment]
Were would the request files be located?
