### ISSUE TITLE
Error when install quickadmin

### ISSUE THREAD

**Issue by tskkh** [LaravelDaily/quickadmin#8]
Hi,

I'm getting an error while running : ` php artisan quickadmin:install`

`SQLSTATE[42000] [1049] Unknown database 'interjob'`.

I just wonder what is that database. Anyone please kindly help.

**Comment by PovilasKorop** [comment]
That is some kind of your internal database. Check your .env file in the main Laravel folder.

**Comment by tskkh** [comment]
Yes thank you PovilasKorop. :+1:
