### ISSUE TITLE
Change from admin to admin.

### ISSUE THREAD

**Issue by jzmwebdevelopment** [LaravelDaily/quickadmin#80]
How can I change the url from /admin to a subdomain? Where is the route file?

**Comment by PovilasKorop** [comment]
Routes file is here: https://github.com/LaravelDaily/quickadmin/blob/master/src/routes.php
And you can change your /admin to /whatever in `config('quickadmin.route')` 

But we don't support subdomains, unfortunately. But you can configure subdomain in your web-server, I guess.
