### ISSUE TITLE
Can we use multiple language interface

### ISSUE THREAD

**Issue by sshekhawat** [LaravelDaily/quickadmin#82]
Hello, 
can i use multiple language interface in quickadmin. if possible then  how  to manage it, please guide me.

**Comment by tpharaoh** [comment]
This question was answered just a moment ago:
https://github.com/LaravelDaily/quickadmin/issues/77

Follow that thread, also Laravel determines languages by App::setLocale($locale);  which you can then set with a drop down for example in your header

**Comment by sshekhawat** [comment]
Thanks for your reply.
