### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by shoully** [LaravelDaily/quickadmin#83]
All these links doesn't work :

http://localhost:8000/users
http://localhost:8000/roles
http://localhost:8000/admin/actions

The error :

1/1 ReflectionException in Container.php line 749:
     Class role does not exist

I test it in laravel (v5.3.16)

**Comment by PovilasKorop** [comment]
You have probably forgotten this instruction item:
`5. Register middleware 'role' => \Laraveldaily\Quickadmin\Middleware\HasPermissions::class, in your App\Http\Kernel.php at $routeMiddleware`

**Comment by shoully** [comment]
Yes, It's working now, I register the middleware before "php artisan quickadmin:instal",
