### ISSUE TITLE
Error parsing single quote

### ISSUE THREAD

**Issue by OliverGrimsley** [LaravelDaily/quickadmin#85]
Somewhere in your code that generates views, you have an error if the user enters a single quote.

Specifics:  I went to add a menu item, called "Employees"  in the first field (text field) in the box that has a placeholder for "field visual title" I entered "Employee's title or position" (note the single quote).  When I went to enter an actual employee, the app throws an error parsing the create.blade.php file for that view for employees - saying it was expecting a ) or ; but that error generated because the single quote was not escaped.

The code your app generated was as follows:

``` php
{!! Form::label('Position', 'Employee's title or position', array('class'=>'col-sm-2 control-label')) !!}
```

It should have generated:

``` php
{!! Form::label('Position', 'Employee\'s title or position', array('class'=>'col-sm-2 control-label')) !!}
```

For now I will remember not to use single quotes, but of course you will want to fix that . . . 

best - mike

**Comment by PovilasKorop** [comment]
Thank you @OliverGrimsley - we will definitely look into it and fix, hopefully next week.
