### ISSUE TITLE
Laravel auth conflict

### ISSUE THREAD

**Issue by PrimusLV** [LaravelDaily/quickadmin#87]
Basically, Quickadmin overwrote Laravel's login page. I know that this is meant to be used with fresh Laravel installation but come on, don't you think that everyone will use domain.com/login for normal users to login?

**Comment by PovilasKorop** [comment]
I assume you're talking about using QuickAdmin for existing project with some front-end already made, so that's NOT what QuickAdmin is for, it is used to generate fresh adminpanel in a fresh Laravel project, not in existing one.

Excerpt from our Readme file:

> Please note: QuickAdmin requires fresh Laravel installation and is not suitable for use on already existing project.
