### ISSUE TITLE
[Error] Menu error when adding a new Parent

### ISSUE THREAD

**Issue by evertramos** [LaravelDaily/quickadmin#88]
I try to add my first parent menu and it did not show in the "Parent menu item" box.

Like that... I create a new parent menu called Tables, where I will add all crud menu for each table, but the Tables Parent Menu did not show in the Menu list.

If I Create two parents it shows the second one normally.

**Comment by ModestasV** [comment]
@evertramos Hello, when you create an empty parent menu item - it should not be visible at all (this means, you wont see it in sidebar and you should see it in the menu manager) but when you add one or more child items to it - it should appear in the sidebar too.

Was this the case of your problem or it just didn't show up when you assigned a child to it? (screenshots would be really helpful here!)

**Comment by evertramos** [comment]
Hi @ModestasV,

What you mentioned was not the case... 

I tried to reproduce the error again and somehow it was solved. 

Thanks anyway. Sorry for taking your time. Maybe was some caching problems...
