### ISSUE TITLE
Error on delete QuickAdmin

### ISSUE THREAD

**Issue by evertramos** [LaravelDaily/quickadmin#89]
Please check delete option on the Admin Panel,

![Screen](https://cloud.githubusercontent.com/assets/905951/20567418/be5e8c38-b17f-11e6-9b2c-378990fd64a9.png)

P.S.: Now I got the screen..

**Comment by ModestasV** [comment]
Hello,

Thank you for reporting this bug. We will check what was wrong with it. In the mean time, could you please provide us some details:
When was this CRUD created?
Which fields it has?

This will help us to check what is wrong.

**Comment by evertramos** [comment]
@ModestasV sorry my late reply...

For the versions 5.3 it´s working ok, but still remains the issue with my old one, which I would like to delete it.

Here it is:

![sem titulo](https://cloud.githubusercontent.com/assets/905951/20796561/ca380838-b7bd-11e6-8f5e-20eb40c2e375.png)


It only has a menu created... trying to delete or add anything comes with error messages as well.

**Comment by PovilasKorop** [comment]
@evertramos thank you for reporting that. The issue with our online version in general that some older adminpanels are now "broken" cause new features didn't regenerate it successfully. Will investigate your particular case in upcoming days.

**Comment by ModestasV** [comment]
@evertramos Hello, no worries about the reply, it is still great to hear more from you!

As for this specific case, we have a safety mechanism in our system which checks if the cruds are not "broker" (for example, a bug caused database table to be deleted but then something messed up). This is the case with older panels as we honestly had some unexpected cases/failures. We are sorry for this error as you can't delete your panel. If you want to remove it completely - confirm that here or write us an email at info@laraveldaily.com with your registration email and we will delete it manually.

Again, sorry for this, we are constantly trying to improve the system and whoopsies like this happen..

**Comment by evertramos** [comment]
@PovilasKorop  @ModestasV  Thanks guys! 

Yes you can remove it for me, thanks for that! 

I will try to keep the tests up on my side.

Cheers!

**Comment by ModestasV** [comment]
@evertramos Removed your panel and changed its name a bit, to clarify that it is broken. Have fun testing!
