### ISSUE TITLE
Conflicting roles table

### ISSUE THREAD

**Issue by Jeroen-G** [LaravelDaily/quickadmin#9]
This package wants to add a roles table, but so do many other packages.
What would be a good way to install the package without a conflict with other packages over the roles table?

**Comment by PovilasKorop** [comment]
Hi @Jeroen-G - good point. Probably we will have to change table name to something like qa_roles to avoid conflict with other packages. What do you think?

**Comment by Jeroen-G** [comment]
Then I would end up with several roles tables.
You should try to decouple it I think. Perhaps you could have a config option for the roles table and model to use. Or publish the migration files, but not executing the migrate command and let people migrate themselves. The core of the solution lies at least in not automatically creating and using a new roles table.

**Comment by Jeroen-G** [comment]
It seems you also copy/overwrite the default User model. Since auth packages (or developers) also interact and change that model, I again think it would be wise to decouple it from your service.
You could create an extra layer between your package and the auth layer which is called by your package and which developers can alter to connect with their auth (or leave to your default).
