### ISSUE TITLE
Error when creating relationship with unique required validation

### ISSUE THREAD

**Issue by Muhammadinaam** [LaravelDaily/quickadmin#91]
When I create a relationship field with **unique** and **required** validation I get following error:

ErrorException in RequestBuilder.php line 115:
Undefined property: stdClass::$relationship_name_id

Please solve this issue

**Comment by ModestasV** [comment]
Hello,
I tagged wrong issue with my latest commit.. it fixes this problem.. Hope you will have no more issues!
