### ISSUE TITLE
Many to Many relation and Number Field

### ISSUE THREAD

**Issue by Muhammadinaam** [LaravelDaily/quickadmin#96]
Online version available at https://quickadminpanel.com/ has more features as compared to this version. As shown in video, online version has Many to Many relationship, Number Field and so many other useful things which are not available in this github version.

My question is, will those feature be added in this version in future? Or we will have to pay for advanced features (available in online version)?

**Comment by PovilasKorop** [comment]
Hi @Muhammadinaam - yes, we're working with full power on the online generator, this free package will be only supported with bug fixes and with new Laravel versions, but not with new features.  

And online generator is not just a generator or a package - it's more like a SERVICE (including customer support with live-chat), so that's what we're charging for, not for the code.

**Comment by Muhammadinaam** [comment]
It means good things are not free :(

**Comment by PovilasKorop** [comment]
@Muhammadinaam yes, good things are not free. We've built the package for free, but instead of thanking us or supporting the onilne version by paying for it, you're blaming us why we don't work more for free. I guess if I go to McDonald's and ask for a burger for free, what would they say.

**Comment by Muhammadinaam** [comment]
But this information should be mentioned that this version does not have features as shown in the video.

On github page of this version, it is being said that check out the online version and there I saw the video and I really liked it. It seems that features shown in video are also available in this version. Then I downloaded this version and noticed that it does not have full features. 

It wasted my 10 days to realize this thing. 

And then I found two **free** laravel admin packages which are far far better than this. 1. Voyager, 2. Laraadmin. They dont think like McDonald's.

**Comment by ModestasV** [comment]
@Muhammadinaam Most of the videos start with a full domain name or an title that it is Online version.

Yes, we are showing the online version as we think that this is the way to go. Package is good and all but it does not reach all of the needed clients. This is why we have different versions as the package version was the beginning and testing the potential.

If you found free tools that do the same - you are free to use them. We are not holding anyone here, we are just offering a tool with support that others may not have (for example live chat).

**Comment by PovilasKorop** [comment]
@Muhammadinaam what can I say - good luck using Voyager and Laraadmin (or any other packages - a lot of them) and expect free support from them. We chose a different path - create an online-service with live-support for our customers and they are happy with it - more than 1500 adminpanels created there already. If 9.99 USD is too much for you to support our idea - then you don't respect our time and we don't have anything else to discuss.
